name: Daily Update

on:
  schedule:
    - cron: '0 5 * * *'  # 毎日JST 14:00（UTC 5:00）に実行
  workflow_dispatch:     # 手動実行も可能

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run YouTube fetch script
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: python bokuao_latest_20.py

    - name: Run HTML generation script
      run: python generate_html.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add boku_ao_latest.csv index.html
        git commit -m "Auto update: $(date '+%Y-%m-%d')"
        git push
